### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: invalid syntax (__init__.py, line 96)

### ISSUE THREAD

**Issue by fancsiko** [trailofbits/algo#1053]
### OS / Environment (where do you run Algo on)

```
Darwin peters-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

### Cloud Provider (where do you deploy Algo to)

```
DigitalOcean
```

### Summary of the problem

Error comes up when I try to deploy algo. I've tried with ./algo and going through the options, with all 'No'-s. I've also tried the scripted deployment.

### Steps to reproduce the behavior

I've had couple of rounds installing, uninstalling different python versions, I think I've finally succeeded in installing it with brew, and then I was able to install virtualenv, then I have created a user in cfg, deleting the original 2 dummies, but haven't changed anything there. Everything then went fine as long as hitting this dead-end during deployment. I try to provide as many details as possible, although I'm not really a developer, or programmer-skilled user, so sorry if I'm not getting something. I have also tried to locate the __init__.py, but since there are a lot within algo-master dir. not sure which one to check for this problem.

### Full log

```
ansible-playbook 2.4.3.0
  config file = /Users/peter/Desktop/algo-master/ansible.cfg
  configured module search path = ['/Users/peter/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible
  executable location = /Users/peter/Desktop/algo-master/env/bin/ansible-playbook
  python version = 3.7.0 (default, Jul 23 2018, 20:24:19) [Clang 9.0.0 (clang-900.0.39.2)]
Using /Users/peter/Desktop/algo-master/ansible.cfg as config file
Parsed /Users/peter/Desktop/algo-master/inventory inventory source with ini plugin
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
ERROR! Unexpected Exception, this is probably a bug: invalid syntax (__init__.py, line 96)
the full traceback was:

Traceback (most recent call last):
  File "/Users/peter/Desktop/algo-master/env/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/executor/playbook_executor.py", line 82, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/__init__.py", line 54, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/__init__.py", line 106, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader)
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/play.py", line 117, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/base.py", line 255, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/play.py", line 197, in _load_roles
    roles.append(Role.load(ri, play=self))
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/role/__init__.py", line 157, in load
    r._load_role_data(role_include, parent_role=parent_role)
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/role/__init__.py", line 211, in _load_role_data
    self._task_blocks = load_list_of_blocks(task_data, play=self._play, role=self, loader=self._loader, variable_manager=self._variable_manager)
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/helpers.py", line 59, in load_list_of_blocks
    loader=loader,
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/block.py", line 86, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/base.py", line 255, in load_data
    self._attributes[name] = method(name, ds[name])
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/block.py", line 122, in _load_block
    use_handlers=self._use_handlers,
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/helpers.py", line 332, in load_list_of_tasks
    t = Task.load(task_ds, block=block, role=role, task_include=task_include, variable_manager=variable_manager, loader=loader)
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/task.py", line 139, in load
    return t.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/base.py", line 245, in load_data
    ds = self.preprocess_data(ds)
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/playbook/task.py", line 179, in preprocess_data
    (action, args, delegate_to) = args_parser.parse()
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/parsing/mod_args.py", line 289, in parse
    if item in module_loader or item in action_loader or item in ['meta', 'include', 'include_tasks', 'include_role', 'import_tasks', 'import_role']:
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/plugins/loader.py", line 323, in has_plugin
    return self.find_plugin(name) is not None
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/plugins/loader.py", line 265, in find_plugin
    for path in (p for p in self._get_paths() if p not in self._searched_paths and os.path.isdir(p)):
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/plugins/loader.py", line 176, in _get_paths
    ret.extend(self._get_package_paths(subdirs=subdirs))
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/plugins/loader.py", line 141, in _get_package_paths
    m = __import__(self.package)
  File "/Users/peter/Desktop/algo-master/env/lib/python3.7/site-packages/ansible/plugins/action/__init__.py", line 96
    if self._task.async and not self._supports_async:
                      ^
SyntaxError: invalid syntax
```

**Comment by jackivanov** [comment]
`python version = 3.7.0`
Not supported actually. Double check the [steps](https://github.com/trailofbits/algo#deploy-the-algo-server), please
