### ISSUE TITLE
Unexpected Exception, this is probably a bug: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by broady** [trailofbits/algo#1118]
**Describe the bug**

I tried running algo installer script on Raspberry Pi running Ubuntu.

Output is "Unexpected Exception, this is probably a bug: [Errno 13] Permission denied".

**To Reproduce**

1. Install Ubuntu Core on Raspberry Pi
2. Install classic mode
3. Follow instructions in README.

**Expected behavior**

Algo installer runs without errors.

**Full log**

```
$ ./algo -vvv
ansible-playbook 2.5.2
  config file = /home/broady/algo/ansible.cfg
  configured module search path = [u'/home/broady/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/broady/algo/env/local/lib/python2.7/site-packages/ansible
  executable location = /home/broady/algo/env/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /home/broady/algo/ansible.cfg as config file
Parsed /home/broady/algo/inventory inventory source with ini pluginERROR! Unexpected Exception, this is probably a bug: [Errno 13] Permission denied
the full traceback was:

Traceback (most recent call last):
  File "/home/broady/algo/env/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/home/broady/algo/env/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 120, in run
    passwords=passwords)
  File "/home/broady/algo/env/local/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 60, in __init__
    self._tqm = TaskQueueManager(inventory=inventory, variable_manager=variable_manager, loader=loader, options=options, passwords=self.passwords)
  File "/home/broady/algo/env/local/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 104, in __init__
    self._final_q = multiprocessing.Queue()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 63, in __init__
    self._rlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
```

```
Algo running on: Ubuntu 16.04.5 LTS
Created from git fork. Last commit: 4a42fbe Move to the ARM deployment schema (#1107)
Python 2.7.12
Runtime variables:
    algo_provider "local"
    algo_ondemand_cellular "False"
    algo_ondemand_wifi "False"
    algo_ondemand_wifi_exclude "_null"
    algo_local_dns "False"
    algo_ssh_tunneling "False"
    algo_windows "False"
    wireguard_enabled "True"
    dns_encryption "True"
```

**Comment by broady** [comment]
I attached strace to the ansible-playbook process, and see this:

```
lstat64("/dev/shm/oZq735", 0x7e9cf938)  = -1 ENOENT (No such file or directory)
open("/dev/shm/oZq735", O_RDWR|O_CREAT|O_EXCL, 0600) = -1 EACCES (Permission denied)
write(2, "\33[0;31mERROR! Unexpected Excepti"..., 93ERROR! Unexpected Exception, this is probably a bug: [Errno 13] Permission denied
```

**Comment by broady** [comment]
Installation seemed to mostly work, up until...

```
TASK [common : Loopback for services configured] *********************************************************************************************************************************************************
changed: [localhost]
failed: [localhost] (item=systemd-networkd) => {"changed": false, "item": "systemd-networkd", "msg": "Service is in unknown state", "status": {}}
failed: [localhost] (item=systemd-resolved) => {"changed": false, "item": "systemd-resolved", "msg": "Service is in unknown state", "status": {}}
```

I suppose it makes sense that root is required to install algo, so that should probably be checked when installing to localhost.

**Comment by jackivanov** [comment]
You didn't include the whole log from your last try

> Raspberry Pi running Ubuntu

What version?

**Comment by broady** [comment]
It's at the bottom of the first message.

```
Algo running on: Ubuntu 16.04.5 LTS
```

**Comment by jackivanov** [comment]
> Ubuntu 16.04.5 LTS

We support only 18.04, sorry

**Comment by broady** [comment]
Can you add some detection for this requirement? It would have been good to know that I just need to get a newer Ubuntu instead of messing around for over an hour :(

Happy to file a different bug.

**Comment by jackivanov** [comment]
It's in the main readme actually https://github.com/trailofbits/algo#features

**Comment by broady** [comment]
It's in the readme *and* I read it, but still, I ended up installing Ubuntu 16.

I assumed that the latest version on Ubuntu's website would be compatible, but it wasn't.

In any case, can you really assume people will read through the entire README?

**Comment by jackivanov** [comment]
All right. Some notes should be added either to the troubleshooting guide or directly to the error message. After an error occurs we need to ask the user to check if they are running the supported system and cloud providers
