### ISSUE TITLE
Update Users fails

### ISSUE THREAD

**Issue by tomtjes** [trailofbits/algo#1444]
**Describe the bug**

Updating users fails on Ubuntu localhost with only WireGuard enabled.
**To Reproduce**

1. cd to folder and enable environment
2. ./algo update-users
3. select server option 1

**Full log**

```
(env) root@XXX:/home/algo# ./algo update-users

PLAY [localhost] ****************************************************************************************************************************************************************************************

TASK [Get list of installed config files] ***************************************************************************************************************************************************************
ok: [localhost]

TASK [Verify servers] ***********************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [Build list of installed servers] ******************************************************************************************************************************************************************
ok: [localhost]
[Server address prompt]
Select the server to update user list below:
    1. XXX
  
:

TASK [Server address prompt] ****************************************************************************************************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] *********************************************************************************************************************************************************************
ok: [localhost]

TASK [Import host specific variables] *******************************************************************************************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] *********************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'user_input'\n\nThe error appears to have been in '/home/algo/users.yml': line 63, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n        - name: Set facts based on the input\n          ^ here\n"}
included: /home/algo/playbooks/rescue.yml for localhost

TASK [debug] ********************************************************************************************************************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] ****************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP **********************************************************************************************************************************************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=2   
```

**Comment by TC1977** [comment]
So I wonder if this is the same undefined variable issue that showed up in #1409 and #1411. Just wondering. What if you go to the `algo` directory and activate virtualenv, then run `ansible-playbook users.yml -e "ca_password=12345"`? (I know you don't have a CA password, since it's a Wireguard-only server, just try '12345' or any string you want.)

**Comment by tomtjes** [comment]
That didn't work. It hung forever at `PLAY [User management]`
```
(env) root@XXX:/home/algo# ansible-playbook users.yml -e "ca_password=12345"

PLAY [localhost] ****************************************************************************************************************************************************************************************

TASK [Get list of installed config files] ***************************************************************************************************************************************************************
ok: [localhost]

TASK [Verify servers] ***********************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [Build list of installed servers] ******************************************************************************************************************************************************************
ok: [localhost]
[Server address prompt]
Select the server to update user list below:
    1. loveservers.reintj.es
  
:
1^M
TASK [Server address prompt] ****************************************************************************************************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] *********************************************************************************************************************************************************************
ok: [localhost]

TASK [Import host specific variables] *******************************************************************************************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] *********************************************************************************************************************************************************************
ok: [localhost]

--> Please include the following block of text when reporting issues:

Algo running on: Ubuntu 18.04.2 LTS (Virtualized: kvm)
Created from git clone. Last commit: ecb4e55 Update users: add server pick-list (#1441)
Python 2.7.15rc1
Runtime variables:
    algo_provider "local"
    algo_local_dns "False"
    algo_ssh_tunneling "False"
    wireguard_enabled "True"
    dns_encryption "True"

TASK [Display the invocation environment] ***************************************************************************************************************************************************************
changed: [localhost -> localhost]

TASK [Install the requirements] *************************************************************************************************************************************************************************
ok: [localhost -> localhost]

TASK [Add the server to the vpn-host group] *************************************************************************************************************************************************************
changed: [localhost]

PLAY [User management] **********************************************************************************************************************************************************************************

^CProcess WorkerProcess-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/algo/env/local/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 118, in run
    self._final_q
  File "/home/algo/env/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/home/algo/env/local/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 612, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/algo/env/local/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/home/algo/env/local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 727, in _execute_module
 [ERROR]: User interrupted execution

    self._make_tmp_path()
  File "/home/algo/env/local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 292, in _make_tmp_path
    tmpdir = self._remote_expand_user(remote_tmp, sudoable=False)
  File "/home/algo/env/local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 595, in _remote_expand_user
    data = self._low_level_execute_command(cmd, sudoable=False)
  File "/home/algo/env/local/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 962, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/home/algo/env/local/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 1145, in exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/home/algo/env/local/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 436, in wrapped
    time.sleep(pause)
KeyboardInterrupt
```
FYI, probably unrelated: I had to install AppArmor manually, when creating the server. I used these instructions: https://github.com/trailofbits/algo/issues/1346#issuecomment-487377987

**Comment by TC1977** [comment]
Looks like you actually got a little bit farther. Do you mind running it with `-vvv` option and see where exactly it hangs?

**Comment by tomtjes** [comment]
Does it try to SSH to itself?
```
PLAY [User management] **********************************************************************************************************************************************************************************
Read vars_file 'config.cfg'
Read vars_file 'configs/{{ inventory_hostname }}/.config.yml'
<myserver.com> ESTABLISH SSH CONNECTION FOR USER: root
<myserver.com> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o ConnectTimeout=6 -o ConnectionAttempts=30 -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=60 -o ControlPath=/root/.ansible/cp/5e85bc8a89 myserver.com '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<myserver.com> (255, '', "Warning: Permanently added 'myserver.com,185.157.234.115' (ECDSA) to the list of known hosts.\r\nroot@myserver.com: Permission denied (publickey,password).\r\n")
<myserver.com> ssh_retry: attempt: 1, ssh return code is 255. cmd (['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'ConnectTimeout=6', '-o', 'ConnectionAttempts=30', '-o', 'IdentitiesOnly=yes', '-o', 'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=60', '-o', 'ControlPath=/root/.ansible/cp/5e85bc8a89', 'myserver.com', "/bin/sh -c 'echo ~root && sleep 0'"]...), pausing for 0 seconds
```

**Comment by TC1977** [comment]
So maybe that's the issue. You're running `update-users` on a local install, right? Maybe it's taking the server domain name instead of 'localhost' from the pick-list and throwing an error.

**Comment by tomtjes** [comment]
> You're running `update-users` on a local install, right?

Correct.

> try `ansible-playbook users.yml -e "ca_password=12345 server=localhost"`

That worked like a charm.
Bonus question: Does it make a difference whether I install Algo locally on the server or from my laptop, letting it do the ssh-ing itself? I tried the latter first, but couldn't get it to work.

**Comment by TC1977** [comment]
@jackivanov I think the second issue also needs fixing. Maybe add follow: yes to the find module at the top? But then people will have to know to pick localhost from the list and not the actual domain or IP.

**Comment by jackivanov** [comment]
I've updated the PR, it shows localhost now
