### ISSUE TITLE
Iptables configured : vultr

### ISSUE THREAD

**Issue by omaritto99** [trailofbits/algo#14656]
**Describe the bug**

i getting a bug at step 'Iptables configured' , im using Vulter 

**Full log**

```
TASK [common : Iptables configured] ******************************************************************************************************************************************************************************
task path: /Users/omar/algo/roles/common/tasks/iptables.yml:2
The full traceback is:
Traceback (most recent call last):
  File "/Users/omar/algo/.env/lib/python3.9/site-packages/ansible/template/__init__.py", line 1001, in do_template
    res = myenv.concat(rf)
  File "/Users/omar/algo/.env/lib/python3.9/site-packages/ansible/template/native_helpers.py", line 83, in ansible_concat
    return ''.join([to_text(v) for v in nodes])
  File "/Users/omar/algo/.env/lib/python3.9/site-packages/ansible/template/native_helpers.py", line 83, in <listcomp>
    return ''.join([to_text(v) for v in nodes])
  File "<template>", line 42, in root
  File "/Users/omar/algo/.env/lib/python3.9/site-packages/ansible/template/__init__.py", line 295, in wrapper
    ret = func(*args, **kwargs)
  File "/Users/omar/algo/.env/lib/python3.9/site-packages/jinja2/filters.py", line 980, in do_int
    return int(value)
  File "/Users/omar/algo/.env/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'wireguard_port_avoid' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omar/algo/.env/lib/python3.9/site-packages/ansible/plugins/action/template.py", line 152, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False, overrides=overrides)
  File "/Users/omar/algo/.env/lib/python3.9/site-packages/ansible/template/__init__.py", line 1035, in do_template
    raise AnsibleUndefinedVariable(e, orig_exc=e)
ansible.errors.AnsibleUndefinedVariable: 'wireguard_port_avoid' is undefined. 'wireguard_port_avoid' is undefined
failed: [64.176.194.204] (item={'src': 'rules.v4.j2', 'dest': '/etc/iptables/rules.v4'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "dest": "/etc/iptables/rules.v4",
        "src": "rules.v4.j2"
    },
    "msg": "AnsibleUndefinedVariable: 'wireguard_port_avoid' is undefined. 'wireguard_port_avoid' is undefined"
}
Read vars_file 'config.cfg'


```

**Comment by omaritto99** [comment]
i got the same error using DigitalOceon : 
<img width="1087" alt="image" src="https://github.com/trailofbits/algo/assets/36052672/f2fbc727-481d-4a04-8855-3a44fc85e212">

**Comment by dguido** [comment]
I think this issue has been long since fixed. Please file again if you encounter it.
