### ISSUE TITLE
Failed to install locally: ERROR! cannot pickle '_io.TextIOWrapper' object

### ISSUE THREAD

**Issue by dexterbrylle** [trailofbits/algo#1819]
I can't seem to install algo on my local machine after verifying that I've met all the pre-requisites.

Machine:

- MacOS Catalina 15.4
- Python 3.8.2

`./algo -vvv` output below
```
ansible-playbook 2.8.8
  config file = /Volumes/Data/Dev/Github/algo/ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Volumes/Data/Dev/Github/algo/.env/lib/python3.8/site-packages/ansible
  executable location = /Volumes/Data/Dev/Github/algo/.env/bin/ansible-playbook
  python version = 3.8.2 (default, Jun  4 2020, 02:07:18) [Clang 11.0.3 (clang-1103.0.32.62)]
Using /Volumes/Data/Dev/Github/algo/ansible.cfg as config file
host_list declined parsing /Volumes/Data/Dev/Github/algo/inventory as it did not pass it's verify_file() method
script declined parsing /Volumes/Data/Dev/Github/algo/inventory as it did not pass it's verify_file() method
auto declined parsing /Volumes/Data/Dev/Github/algo/inventory as it did not pass it's verify_file() method
Parsed /Volumes/Data/Dev/Github/algo/inventory inventory source with ini plugin
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
statically imported: /Volumes/Data/Dev/Github/algo/playbooks/cloud-pre.yml
Read vars_file 'config.cfg'
statically imported: /Volumes/Data/Dev/Github/algo/playbooks/cloud-post.yml
Read vars_file 'config.cfg'
statically imported: /Volumes/Data/Dev/Github/algo/playbooks/tmpfs/main.yml
Read vars_file 'config.cfg'
statically imported: /Volumes/Data/Dev/Github/algo/playbooks/tmpfs/macos.yml
Read vars_file 'config.cfg'
statically imported: /Volumes/Data/Dev/Github/algo/playbooks/tmpfs/linux.yml
Read vars_file 'config.cfg'
[WARNING]: Could not match supplied host pattern, ignoring: vpn-host

Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
statically imported: /Volumes/Data/Dev/Github/algo/roles/dns/tasks/dns_adblocking.yml
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
statically imported: /Volumes/Data/Dev/Github/algo/roles/wireguard/tasks/keys.yml
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
statically imported: /Volumes/Data/Dev/Github/algo/roles/strongswan/tasks/ipsec_configuration.yml
Read vars_file 'config.cfg'
statically imported: /Volumes/Data/Dev/Github/algo/roles/strongswan/tasks/openssl.yml
Read vars_file 'config.cfg'
statically imported: /Volumes/Data/Dev/Github/algo/roles/strongswan/tasks/distribute_keys.yml
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
statically imported: /Volumes/Data/Dev/Github/algo/roles/strongswan/tasks/client_configs.yml
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
Read vars_file 'config.cfg'
statically imported: /Volumes/Data/Dev/Github/algo/playbooks/tmpfs/umount.yml
Read vars_file 'config.cfg'

PLAYBOOK: main.yml *********************************************************************************
4 plays in main.yml

PLAY [localhost] ***********************************************************************************
ERROR! Unexpected Exception, this is probably a bug: cannot pickle '_io.TextIOWrapper' object
the full traceback was:

Traceback (most recent call last):
  File "/Volumes/Data/Dev/Github/algo/.env/bin/ansible-playbook", line 110, in <module>
    exit_code = cli.run()
  File "/Volumes/Data/Dev/Github/algo/.env/lib/python3.8/site-packages/ansible/cli/playbook.py", line 123, in run
    results = pbex.run()
  File "/Volumes/Data/Dev/Github/algo/.env/lib/python3.8/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/Volumes/Data/Dev/Github/algo/.env/lib/python3.8/site-packages/ansible/executor/task_queue_manager.py", line 249, in run
    play_return = strategy.run(iterator, play_context)
  File "/Volumes/Data/Dev/Github/algo/.env/lib/python3.8/site-packages/ansible/plugins/strategy/linear.py", line 306, in run
    self._queue_task(host, task, task_vars, play_context)
  File "/Volumes/Data/Dev/Github/algo/.env/lib/python3.8/site-packages/ansible/plugins/strategy/__init__.py", line 317, in _queue_task
    worker_prc.start()
  File "/Volumes/Data/Dev/Github/algo/.env/lib/python3.8/site-packages/ansible/executor/process/worker.py", line 96, in start
    return super(WorkerProcess, self).start()
  File "/Users/user/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/user/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/user/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/user/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/user/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/user/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/user/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object

/Volumes/Data/Dev/Github/algo master
.env ❯ ./algo
[WARNING]: Could not match supplied host pattern, ignoring: vpn-host


PLAY [localhost] ***********************************************************************************
ERROR! Unexpected Exception, this is probably a bug: cannot pickle '_io.TextIOWrapper' object
to see the full traceback, use -vvv
```

**Comment by davidemyers** [comment]
The [README](https://github.com/trailofbits/algo#deploy-the-algo-server) says:
>Download and install the latest stable [Python 3.7.x package](https://www.python.org/downloads/mac-osx/) (currently Python 3.8 will not work). 

The [documentation for deploying from macOS](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-macos.md#deploy-from-macos) says:
>**IMPORTANT:** At this time you **cannot** use Python 3.8 or later with Ansible on macOS. Choose a recent version of Python 3.7 instead.
