### ISSUE TITLE
Fix for DO scripted deploys (ssh_keys.changed)

### ISSUE THREAD

**Issue by onpaws** [trailofbits/algo#217]
Algo is a sweet project, thanks for your hustle here!
Just wanted to share a simple fix for a blocker I encountered today. It's an immediate fix for a [commit](https://github.com/trailofbits/algo/commit/33b3af540a0a2cf28f0149d7bdc99f779fe6d233) that in my anecdotal was breaking scripted deploys to DigitalOcean.

This is the error, as seen both by `./algo` and `ansible-playbook` invocation:
```
error while evaluating conditional (ssh_keys.changed != 1): 'dict object' has no attribute 'changed'"}
```

If anyone else wishes to resolve right now:
1) Comment out the line with `ssh_keys.changed`, currently it's [here](https://github.com/trailofbits/algo/blob/master/roles/cloud-digitalocean/tasks/main.yml#L13)
1) You may need to manually run `pip install six dopy` (I did)

and you'll be all set.

### OS / Environment
macOS 10.12.2

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`
```
ansible>=2.1
dopy==0.3.5
boto>=2.5
boto3
azure==2.0.0rc5
apache-libcloud
six
pyopenssl
```

### Summary of the problem
DO scripted deploys don't work.

### Steps to reproduce the behavior
1) Retrieve a DigitalOcean API Key 
1) `brew install ansible` etc/whatever deps your system needs
1) Ran the provided [sample](https://github.com/trailofbits/algo/blob/master/docs/ADVANCED.md#scripted-deployment) as provided on the [latest commit](https://github.com/trailofbits/algo/commit/2798f84d3fdbaf8289ebbe9ec384a266d8ad4b1d)   available at time of writing:
```
ansible-playbook deploy.yml -t digitalocean,vpn,cloud -e 'do_access_token=my_secret_token do_server_name=algo.local do_region=ams2'
```
(Obviously replace 'my_secret_token' with a real API key)

### The way of deployment (cloud or local)
Cloud on DigitalOcean

### Expected behavior
Provided deploy sample works.

### Actual behavior
Provided deploy sample fails.

### Full log
```
PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost -> localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost -> localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost -> localhost]

TASK [cloud-digitalocean : Set the DigitalOcean Access Token fact] *************
ok: [localhost]

TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "dopy >= 0.3.2 is required for this module.  dopy requires six but six is not installed.  Make sure both dopy and six are installed."}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1   
```

**Comment by gunph1ld** [comment]
So, this issue includes 2 errors, the first one is a bug. @onpaws  try to uncomment the lines you commented out and invoke ansible-playbook with the `-vvvv` flags, then attach the log here.

The second error (in your full log) is not a bug. You have to check this - [README#deploy-the-algo-server](https://github.com/trailofbits/algo#deploy-the-algo-server)

**Comment by onpaws** [comment]
Thanks @gunph1ld!
Here's what `-vvvv` reveals; I'm understanding this output right looks like SSH auth.

```
<999.999.999.999> ESTABLISH SSH CONNECTION FOR USER: root
<999.999.999.999> SSH: EXEC ssh -vvv -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o ConnectTimeout=6 -o ConnectionAttempts=30 -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o 'IdentityFile="configs/algo.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=60 -o ControlPath=/Users/paws/.ansible/cp/ansible-ssh-%h-%p-%r -tt 999.999.999.999 'sleep 10 && sudo apt-get update -qq && sudo apt-get install -qq -y python2.7'
fatal: [999.999.999.999]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.3p1, LibreSSL 2.4.1\r\ndebug1: Reading configuration data /Users/paws/.ssh/config\r\ndebug1: /Users/paws/.ssh/config line 50: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/Users/paws/.ansible/cp/ansible-ssh-999.999.999.999-22-root\" does not exist\r\ndebug2: resolving \"999.999.999.999\" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to 999.999.999.999 [999.999.999.999] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: fd 3 clearing O_NONBLOCK\r\ndebug1: Connection established.\r\ndebug3: timeout: 5925 ms remain after connect\r\ndebug1: identity file configs/algo.pem type 1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file configs/algo.pem-cert type -1\r\ndebug1: Enabling compatibility mode for protocol 2.0\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.3\r\ndebug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.1\r\ndebug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1 pat OpenSSH* compat 0x04000000\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: Authenticating to 999.999.999.999:22 as 'root'\r\ndebug3: hostkeys_foreach: reading file \"/dev/null\"\r\ndebug3: send packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT sent\r\ndebug3: receive packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT received\r\ndebug2: local client KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c\r\ndebug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: none,zlib@openssh.com,zlib\r\ndebug2: compression stoc: none,zlib@openssh.com,zlib\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug2: peer server KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1\r\ndebug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: none,zlib@openssh.com\r\ndebug2: compression stoc: none,zlib@openssh.com\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug1: kex: algorithm: curve25519-sha256@libssh.org\r\ndebug1: kex: host key algorithm: ecdsa-sha2-nistp256\r\ndebug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none\r\ndebug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none\r\ndebug3: send packet: type 30\r\ndebug1: expecting SSH2_MSG_KEX_ECDH_REPLY\r\ndebug3: receive packet: type 31\r\ndebug1: Server host key: ecdsa-sha2-nistp256 SHA256:MIG75ga/sJvweS0MWqm9hkVoys67gw4z2qI5OCG1s88\r\ndebug3: hostkeys_foreach: reading file \"/dev/null\"\r\nWarning: Permanently added '999.999.999.999' (ECDSA) to the list of known hosts.\r\ndebug3: send packet: type 21\r\ndebug2: set_newkeys: mode 1\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS sent\r\ndebug1: expecting SSH2_MSG_NEWKEYS\r\ndebug3: receive packet: type 21\r\ndebug2: set_newkeys: mode 0\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS received\r\ndebug2: key: configs/algo.pem (0x7fb58f0005c0), explicit\r\ndebug3: send packet: type 5\r\ndebug3: receive packet: type 7\r\ndebug1: SSH2_MSG_EXT_INFO received\r\ndebug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>\r\ndebug3: receive packet: type 6\r\ndebug2: service_accept: ssh-userauth\r\ndebug1: SSH2_MSG_SERVICE_ACCEPT received\r\ndebug3: send packet: type 50\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey,password\r\ndebug3: start over, passed a different list publickey,password\r\ndebug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_lookup publickey\r\ndebug3: remaining preferred: ,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_is_enabled publickey\r\ndebug1: Next authentication method: publickey\r\ndebug1: Offering RSA public key: configs/algo.pem\r\ndebug3: send_pubkey_test\r\ndebug3: send packet: type 50\r\ndebug2: we sent a publickey packet, wait for reply\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey,password\r\ndebug2: we did not send a packet, disable method\r\ndebug1: No more authentication methods to try.\r\nPermission denied (publickey,password).\r\n", 
    "unreachable": true
}

PLAY RECAP *********************************************************************
999.999.999.999               : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=12   changed=3    unreachable=0    failed=0   

999.999.999.999
```

(masked the IP with 9s)

**Comment by gunph1ld** [comment]
1. It is not the error you mentioned abouve `error while evaluating conditional (ssh_keys.changed`
2. I can't reproduce this error
3. You have to show the full log

**Comment by onpaws** [comment]
Starting to suspect the first issue, the `ssh_keys.changed` may have been related to missing dependencies, e.g. six, dopy? 
When I get a moment I'll figure out a way to recreate a clean starting environment.

**Comment by gunph1ld** [comment]
Any updates? @onpaws

**Comment by onpaws** [comment]
Out of town for weekend. Aim to get back to you Tuesday, appreciate the follow up!

**Comment by 9Yg1rxeSeha90ZU1** [comment]
keys successfully changed and still saw this error:

```
PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
changed: [localhost -> localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost -> localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost -> localhost]

TASK [cloud-digitalocean : Set the DigitalOcean Access Token fact] *************
ok: [localhost]

TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'ssh_keys.changed != 1' failed. The error was: error while evaluating conditional (ssh_keys.changed != 1): 'dict object' has no attribute 'changed'"}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1   

```

**Comment by 9Yg1rxeSeha90ZU1** [comment]
can confirm that commenting out this one yml line allows to bypass the error

```
...
#until: ssh_keys.changed != 1
...
```

**Comment by gunph1ld** [comment]
I need to see the output of ansible-playbook with `-vvvv` flags

**Comment by 9Yg1rxeSeha90ZU1** [comment]
testing in a sandbox droplet this is the output from the last command modified to append -vvvv to any ansible-playbook command

```
TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
task path: /root/tools/algo/roles/cloud-digitalocean/tasks/main.yml:6
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/cloud/digital_ocean/digital_ocean.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485944235.63-274203305485789 `" && echo ansible-tmp-1485944235.63-274203305485789="` echo ~/.ansible/tmp/ansible-tmp-1485944235.63-274203305485789 `" ) && sleep 0'
<localhost> PUT /tmp/tmpWT6mHR TO /root/.ansible/tmp/ansible-tmp-1485944235.63-274203305485789/digital_ocean.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1485944235.63-274203305485789/ /root/.ansible/tmp/ansible-tmp-1485944235.63-274203305485789/digital_ocean.py && sleep 0'
<localhost> EXEC /bin/sh -c 'python /root/.ansible/tmp/ansible-tmp-1485944235.63-274203305485789/digital_ocean.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1485944235.63-274203305485789/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "The conditional check 'ssh_keys.changed != 1' failed. The error was: error while evaluating conditional (ssh_keys.changed != 1): 'dict object' has no attribute 'changed'"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1   

```

**Comment by 9Yg1rxeSeha90ZU1** [comment]
and from ssh-keygen

```
TASK [Generate the SSH private key] ********************************************
task path: /root/tools/algo/playbooks/local.yml:3
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/commands/command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485944234.57-8492916007705 `" && echo ansible-tmp-1485944234.57-8492916007705="` echo ~/.ansible/tmp/ansible-tmp-1485944234.57-8492916007705 `" ) && sleep 0'
<localhost> PUT /tmp/tmpAkvNbe TO /root/.ansible/tmp/ansible-tmp-1485944234.57-8492916007705/command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1485944234.57-8492916007705/ /root/.ansible/tmp/ansible-tmp-1485944234.57-8492916007705/command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'python /root/.ansible/tmp/ansible-tmp-1485944234.57-8492916007705/command.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1485944234.57-8492916007705/" > /dev/null 2>&1 && sleep 0'
changed: [localhost -> localhost] => {
    "changed": true, 
    "cmd": "echo -e 'n' | ssh-keygen -b 2048 -C algo@ssh -t rsa -f configs/algo.pem -q -N \"\"", 
    "delta": "0:00:00.172634", 
    "end": "2017-02-01 10:17:14.867585", 
    "invocation": {
        "module_args": {
            "_raw_params": "echo -e 'n' | ssh-keygen -b 2048 -C algo@ssh -t rsa -f configs/algo.pem -q -N \"\"", 
            "_uses_shell": true, 
            "chdir": null, 
            "creates": "configs/algo.pem", 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "command"
    }, 
    "rc": 0, 
    "start": "2017-02-01 10:17:14.694951", 
    "stderr": "", 
    "stdout": "", 
    "stdout_lines": [], 
    "warnings": []
}

```

**Comment by 9Yg1rxeSeha90ZU1** [comment]
error seems reproducible when API key is read-only or the DO API server sends an incorrect / invalid response. maybe there can be better error handling to detect those earlier or as exceptions and let the user know

**Comment by gunph1ld** [comment]
Sorry, @9Yg1rxeSeha90ZU1 can you comment out `until: ssh_keys.changed != 1` and try with `-vvvv` again

**Comment by 9Yg1rxeSeha90ZU1** [comment]
```
TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
task path: /root/tools/algo/roles/cloud-digitalocean/tasks/main.yml:6
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/cloud/digital_ocean/digital_ocean.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485945544.51-135139093361691 `" && echo ansible-tmp-1485945544.51-135139093361691="` echo ~/.ansible/tmp/ansible-tmp-1485945544.51-135139093361691 `" ) && sleep 0'
<localhost> PUT /tmp/tmptHVxeb TO /root/.ansible/tmp/ansible-tmp-1485945544.51-135139093361691/digital_ocean.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1485945544.51-135139093361691/ /root/.ansible/tmp/ansible-tmp-1485945544.51-135139093361691/digital_ocean.py && sleep 0'
<localhost> EXEC /bin/sh -c 'python /root/.ansible/tmp/ansible-tmp-1485945544.51-135139093361691/digital_ocean.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1485945544.51-135139093361691/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_HGtjwB/ansible_module_digital_ocean.py", line 464, in main
    core(module)
  File "/tmp/ansible_HGtjwB/ansible_module_digital_ocean.py", line 420, in core
    key.destroy()
  File "/tmp/ansible_HGtjwB/ansible_module_digital_ocean.py", line 308, in destroy
    self.manager.destroy_ssh_key(self.id)
  File "/usr/local/lib/python2.7/dist-packages/dopy/manager.py", line 346, in destroy_ssh_key
    self.request('/account/keys/%s' % key_id, method='DELETE')
  File "/usr/local/lib/python2.7/dist-packages/dopy/manager.py", line 467, in request
    resp = self.request_v2(url, params=params, headers=headers, method=method)
  File "/usr/local/lib/python2.7/dist-packages/dopy/manager.py", line 22, in wrapper
    return func(self, url, headers, params, method)
  File "/usr/local/lib/python2.7/dist-packages/dopy/manager.py", line 535, in request_v2
    resp.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden for url: https://api.digitalocean.com/v2/account/keys/5364536

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "backups_enabled": false, 
            "command": "ssh", 
            "id": null, 
            "image_id": null, 
            "ipv6": false, 
            "name": "algo@ssh", 
            "private_networking": false, 
            "region_id": null, 
            "size_id": null, 
            "ssh_key_ids": null, 
            "ssh_pub_key": null, 
            "state": "absent", 
            "unique_name": false, 
            "user_data": null, 
            "virtio": true, 
            "wait": true, 
            "wait_timeout": 300
        }, 
        "module_name": "digital_ocean"
    }, 
    "msg": "403 Client Error: Forbidden for url: https://api.digitalocean.com/v2/account/keys/5364536"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1  
```

**Comment by gunph1ld** [comment]
@9Yg1rxeSeha90ZU1 what version of dopy?
`pip show dopy`

**Comment by 9Yg1rxeSeha90ZU1** [comment]
0.3.7

**Comment by gunph1ld** [comment]
I was trying to reproduce the bug, but couldn't catch it. 
It look like as a security issue on DO, do you use a team account or personal?
Can you check the 'Security history' in your DO account (team or personal)?

**Comment by 9Yg1rxeSeha90ZU1** [comment]
dont think so. like i mentioned, if you use a READ ONLY api key then obviously it will fail with this error (because it does not have WRITE access to create a new droplet). you should probably check that and let the user know. but, the same error could cause the traceback if you got a 500 http status return code due to api server failure.

**Comment by onpaws** [comment]
Thanks for following up on this.
I just pulled the latest commit off master, deployed a new DO droplet and it worked fine. (yay!)

I've always used a R/W API key. Perhaps @9Yg1rxeSeha90ZU1 has a different issue than me?
![image](https://cloud.githubusercontent.com/assets/182515/22519000/ca526cec-e87c-11e6-9adf-2e1e4300a9af.png)

Regardless it seems like my machine now has whatever dependencies caused my original error so I'm unable to easily repro. 
I suspect the issue may return next time I use Algo on a clean Sierra install -- if so I'll post back here.

Thanks @gunph1ld for clarifying the error, I hope it helps future users.

**Comment by leppert** [comment]
I'm seeing the same issue using master (https://github.com/trailofbits/algo/commit/f0283856ad52780157e5111ee8dc786cdae8e2d8) with a read+write Digital Ocean token. Running `pip list` shows `dopy (0.3.5)` installed.

```
TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'ssh_keys.changed != true' failed. The error was: error while evaluating conditional (ssh_keys.changed != true): 'dict object' has no attribute 'changed'"}

TASK [cloud-digitalocean : Collect the fail error] *****************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "dopy >= 0.3.2 required for this module"}
...ignoring

TASK [cloud-digitalocean : debug] **********************************************
ok: [localhost] => {
    "ssh_keys": {
        "changed": false,
        "failed": true,
        "msg": "dopy >= 0.3.2 required for this module"
    }
}

TASK [cloud-digitalocean : fail] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Please, ensure that your API token is not read-only."}

TASK [cloud-digitalocean : debug] **********************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-digitalocean : fail] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=9    changed=0    unreachable=0    failed=1
```

**Comment by lookfirst** [comment]
Ran into this same weirdness as well. 

Had to run the virtualenv stuff first... basically created a script that looks like this:

```
#!/usr/bin/env bash

set -e

DO_ACCESS_TOKEN='YOUR_DO_TOKEN'

mkdir -p configs

python -m virtualenv env && source env/bin/activate && python -m pip install -U pip && python -m pip install -r requirements.txt

ansible-playbook deploy.yml -t digitalocean,vpn,cloud,security \
	-e "do_access_token=${DO_ACCESS_TOKEN} do_server_name=algo.local do_region=nyc3 OnDemandEnabled_Cellular=Y OnDemandEnabled_WIFI=Y OnDemandEnabled_WIFI_EXCLUDE='HomeNet' Store_CAKEY=N" \
	--skip-tags _null,encrypted
```

Obviously use your own settings for the configuration of the playbook. =)
