### ISSUE TITLE
Unexpected Exception: jinja2<2.9 Error

### ISSUE THREAD

**Issue by bdwilson** [trailofbits/algo#220]
### OS / Environment

Raspberry Pi / Rasbian 7

### Ansible version
2.2.1.0

### Version of components from `requirements.txt`
ansible>=2.1
dopy==0.3.5
boto>=2.5
boto3
azure==2.0.0rc5
apache-libcloud
six
pyopenssl
jinja2<2.9  (added this one to try and resolve the issue).

### Summary of the problem
Cannot complete installation.  Finish all the questions, ten in about 10 seconds, I get this error: ERROR! Unexpected Exception: jinja2<2.9

Tried pip uninstalling jinja2, then re-installing (which gave me 2.9.4). 

Also tried adding jinja2<2.9 to requirements and it installed 2.8.1, same issue.

Wondering if this is somehow related? https://github.com/ansible/ansible/issues/20285 

### Steps to reproduce the behavior

Attempt install on Raspbian 7. 

### The way of deployment (cloud or local)

Local install, local RaspberryPI

### Full log

$ ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Google Compute Engine
    4. Microsoft Azure
    5. Install to existing Ubuntu server

Enter the number of your desired provider
: 5

Enter IP address of your server: (use localhost for local installation)
: localhost

What user should we use to login on the server? (ignore if you're deploying to localhost)
[root]:

Enter the public IP address of your server: (IMPORTANT! This IP is used to verify the certificate)
: xxx.xxx.xxx.xxx

Do you want to enable VPN Always-On when connected to cellular networks?
[y/N]:

Do you want to enable VPN Always-On when connected to Wi-Fi?
[y/N]:

Do you want to install a local DNS resolver to block ads while surfing?
[y/N]:

Do you want each user to have their own account for SSH tunneling?
[y/N]:

Do you want to apply operating system security enhancements on the server?
[y/N]:

Do you want the VPN to support Windows 10 clients? (requires RSA certificates and key exchange, less secure)
[y/N]:
Using /home/pi/git/algo/ansible.cfg as config file
statically included: /home/pi/git/algo/roles/cloud-ec2/tasks/encrypt_image.yml
statically included: /home/pi/git/algo/playbooks/local.yml
statically included: /home/pi/git/algo/roles/vpn/tasks/iptables.yml
statically included: /home/pi/git/algo/playbooks/common.yml
ERROR! Unexpected Exception: jinja2<2.9
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 159, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 89, in run
    self._tqm.load_callbacks()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 177, in load_callbacks
    for callback_plugin in callback_loader.all(class_only=True):
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 394, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 324, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/foreman.py", line 30, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 48, in <module>
    from cryptography import x509
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/base.py", line 15, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, ec, rsa
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
DistributionNotFound: jinja2<2.9

**Comment by gunph1ld** [comment]
`pip install --ignore-install -r requirements.txt` and try again, please

**Comment by bdwilson** [comment]
Thanks that resolved the issue for Jinja. Will open another issue for missing package
