### ISSUE TITLE
ValueError: ('Expected version spec in', 'msrest ~=0.4.4', 'at', ' ~=0.4.4') on Ubuntu 14.04

### ISSUE THREAD

**Issue by acidas** [trailofbits/algo#387]
### OS / Environment
self-hosted KVM VM
Ubuntu 14.04

### Ansible version
none

### Version of components from `requirements.txt`
setuptools=2.2
Can't show other packages, because they're not installed due to msrest error

### Summary of the problem
```python -m pip install -r requirements.txt``` throws the same error as:
```(env)root@host:~/algo-master# pip install msrest=0.4.4```
```Exception:
Traceback (most recent call last):
  File "/root/algo-master/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/root/algo-master/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/root/algo-master/env/local/lib/python2.7/site-packages/pip/req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/root/algo-master/env/local/lib/python2.7/site-packages/pip/req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/root/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2606, in parse
    reqs = list(parse_requirements(s))
  File "/root/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2544, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/root/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2512, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'msrest=0.4.4', 'at', '=0.4.4')

Storing debug log for failure in /root/.pip/pip.log
```

### Steps to reproduce the behavior
Try to follow install steps on Ubuntu 14.04

### The way of deployment (cloud or local)
Local

**Comment by dguido** [comment]
We don't support Ubuntu 14.04

**Comment by acidas** [comment]
Is there any list of supported distros with versions?

**Comment by dguido** [comment]
yes

**Comment by acidas** [comment]
Can't find it, could you share the link?

**Comment by dguido** [comment]
You should have been prompted with it before filing an issue:

https://github.com/trailofbits/algo/blob/master/CONTRIBUTING.md

**Comment by acidas** [comment]
Can't find the list of supported distros for server in your link, nor in FAQ, Troubleshooting or known issues.

**Comment by acidas** [comment]
Which distro do you suggest for server?

**Comment by fma16** [comment]
@acidas Are you looking for this?
> We only support modern operating systems, e.g. macOS 10.11+, iOS 9+, Windows 10+, Ubuntu 17.04+, etc.

**Comment by acidas** [comment]
I thought these are for clients:
```e.g. macOS 10.11+, iOS 9+, Windows 10+, Ubuntu 17.04+, etc.```

Will try to set up server on Ubuntu 17.04
