### ISSUE TITLE
mrest package doesn't exist anywhere

### ISSUE THREAD

**Issue by thelostt** [trailofbits/algo#401]
### OS / Environment
    $ uname -a
    Linux iZ62p8yih7zZ 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

### Ansible version
ansible 1.5.4

### Version of components from `requirements.txt`

Can't install any package.

### Summary of the problem

    ValueError: ('Expected version spec in', 'msrest ~=0.4.4', 'at', ' ~=0.4.4')

And `pip search mrest` doesn't come up with anything.

### Steps to reproduce the behavior

Clone repository, go through steps from `README.md` untill 4th step. Try:

    python -m virtualenv env && source env/bin/activate && python -m pip install -r requirements.txt

And fail with exception being thrown:

```
Exception:
Traceback (most recent call last):
  File "/algo-master/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/algo-master/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/algo-master/env/local/lib/python2.7/site-packages/pip/req.py", line 1265, in prepare_files
    req_to_install.extras):
  File "/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2232, in requires
    dm = self._dep_map
  File "/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2423, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2447, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 45, in <lambda>
    next = lambda o: o.next()
  File "/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2544, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2512, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'msrest ~=0.4.4', 'at', ' ~=0.4.4')
```

### The way of deployment (cloud or local)

It's a server.

### Expected behavior

Installed packages.

### Actual behavior

`mrest` makes installation process misbehave and prevents anything from continuing.

### Full log

Can't run algo.

**Comment by thelostt** [comment]
Closed as typo issues.
