### ISSUE TITLE
./algo error

### ISSUE THREAD

**Issue by kevingrijalva** [trailofbits/algo#636]
### OS / Environment

Amazon EC2

### Ansible version

ansible 2.0.0.2
config file = /home/algo/ansible.cfg
configured module search path = Default w/o overrides

### Version of components from `requirements.txt`
after running pip install -r requirements.txt I got:

Collecting msrestazure (from -r requirements.txt (line 1))
  Using cached msrestazure-0.4.11-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=11.3 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Collecting ansible<2.2.1,>=2.1 (from -r requirements.txt (line 3))
  Downloading ansible-2.2.0.0.tar.gz (2.4MB)
    100% |████████████████████████████████| 2.4MB 468kB/s
Collecting dopy==0.3.5 (from -r requirements.txt (line 4))
Collecting boto>=2.5 (from -r requirements.txt (line 5))
  Using cached boto-2.48.0-py2.py3-none-any.whl
Collecting boto3 (from -r requirements.txt (line 6))
  Using cached boto3-1.4.4-py2.py3-none-any.whl
Collecting azure==2.0.0rc5 (from -r requirements.txt (line 7))
  Using cached azure-2.0.0rc5-py2.py3-none-any.whl
Collecting msrest==0.4.1 (from -r requirements.txt (line 8))
  Using cached msrest-0.4.1-py2-none-any.whl
Collecting apache-libcloud (from -r requirements.txt (line 9))
  Using cached apache_libcloud-2.1.0-py2.py3-none-any.whl
Collecting six (from -r requirements.txt (line 10))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pyopenssl (from -r requirements.txt (line 11))
  Using cached pyOpenSSL-17.2.0-py2.py3-none-any.whl
Collecting jinja2==2.8 (from -r requirements.txt (line 12))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting keyring>=5.6 (from msrestazure->-r requirements.txt (line 1))
  Using cached keyring-10.4.0-py2.py3-none-any.whl
Collecting adal~=0.4.0 (from msrestazure->-r requirements.txt (line 1))
Collecting paramiko (from ansible<2.2.1,>=2.1->-r requirements.txt (line 3))
  Using cached paramiko-2.2.1-py2.py3-none-any.whl
Collecting PyYAML (from ansible<2.2.1,>=2.1->-r requirements.txt (line 3))
Collecting pycrypto>=2.6 (from ansible<2.2.1,>=2.1->-r requirements.txt (line 3))
Collecting requests>=1.0.4 (from dopy==0.3.5->-r requirements.txt (line 4))
  Using cached requests-2.18.2-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3->-r requirements.txt (line 6))
  Using cached s3transfer-0.1.10-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->-r requirements.txt (line 6))
  Using cached jmespath-0.9.3-py2.py3-none-any.whl
Collecting botocore<1.6.0,>=1.5.0 (from boto3->-r requirements.txt (line 6))
  Downloading botocore-1.5.88-py2.py3-none-any.whl (3.6MB)
    100% |████████████████████████████████| 3.6MB 84kB/s
Collecting azure-batch==0.30.0rc5 (from azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_batch-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-servicemanagement-legacy==0.20.3 (from azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_servicemanagement_legacy-0.20.3-py2.py3-none-any.whl
Collecting azure-graphrbac==0.30.0rc5 (from azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_graphrbac-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-storage==0.32.0 (from azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_storage-0.32.0-py2-none-any.whl
Collecting azure-mgmt==0.30.0rc5 (from azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-servicebus==0.20.2 (from azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_servicebus-0.20.2-py2.py3-none-any.whl
Collecting certifi>=2015.9.6.2 (from msrest==0.4.1->-r requirements.txt (line 8))
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting chardet>=2.3.0 (from msrest==0.4.1->-r requirements.txt (line 8))
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting requests-oauthlib>=0.5.0 (from msrest==0.4.1->-r requirements.txt (line 8))
  Using cached requests_oauthlib-0.8.0-py2.py3-none-any.whl
Collecting enum34>=1.0.4 (from msrest==0.4.1->-r requirements.txt (line 8))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting isodate>=0.5.4 (from msrest==0.4.1->-r requirements.txt (line 8))
Collecting cryptography>=1.9 (from pyopenssl->-r requirements.txt (line 11))
  Using cached cryptography-2.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting MarkupSafe (from jinja2==2.8->-r requirements.txt (line 12))
Collecting secretstorage; sys_platform == "linux2" or sys_platform == "linux" (from keyring>=5.6->msrestazure->-r requirements.txt (line 1))
Collecting python-dateutil>=2.1.0 (from adal~=0.4.0->msrestazure->-r requirements.txt (line 1))
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting PyJWT>=1.0.0 (from adal~=0.4.0->msrestazure->-r requirements.txt (line 1))
  Using cached PyJWT-1.5.2-py2.py3-none-any.whl
Collecting pynacl>=1.0.1 (from paramiko->ansible<2.2.1,>=2.1->-r requirements.txt (line 3))
  Using cached PyNaCl-1.1.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pyasn1>=0.1.7 (from paramiko->ansible<2.2.1,>=2.1->-r requirements.txt (line 3))
  Using cached pyasn1-0.2.3-py2.py3-none-any.whl
Collecting bcrypt>=3.1.3 (from paramiko->ansible<2.2.1,>=2.1->-r requirements.txt (line 3))
  Using cached bcrypt-3.1.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting idna<2.6,>=2.5 (from requests>=1.0.4->dopy==0.3.5->-r requirements.txt (line 4))
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=1.0.4->dopy==0.3.5->-r requirements.txt (line 4))
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" (from s3transfer<0.2.0,>=0.1.10->boto3->-r requirements.txt (line 6))
  Using cached futures-3.1.1-py2-none-any.whl
Collecting docutils>=0.10 (from botocore<1.6.0,>=1.5.0->boto3->-r requirements.txt (line 6))
  Using cached docutils-0.13.1-py2-none-any.whl
Collecting azure-common[autorest]==1.1.4 (from azure-batch==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_common-1.1.4-py2.py3-none-any.whl
Collecting azure-nspkg (from azure-storage==0.32.0->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_nspkg-2.0.0-py2.py3-none-any.whl
Collecting azure-mgmt-cdn==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_cdn-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-powerbiembedded==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_powerbiembedded-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-notificationhubs==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_notificationhubs-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-authorization==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_authorization-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-batch==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_batch-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-storage==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_storage-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-resource==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_resource-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-web==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_web-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-network==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_network-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-logic==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_logic-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-keyvault==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_keyvault-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-scheduler==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_scheduler-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-compute==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_compute-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-cognitiveservices==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_cognitiveservices-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-redis==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_redis-0.30.0rc5-py2.py3-none-any.whl
Collecting azure-mgmt-commerce==0.30.0rc5 (from azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_commerce-0.30.0rc5-py2.py3-none-any.whl
Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.5.0->msrest==0.4.1->-r requirements.txt (line 8))
Collecting ipaddress (from cryptography>=1.9->pyopenssl->-r requirements.txt (line 11))
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.9->pyopenssl->-r requirements.txt (line 11))
  Using cached asn1crypto-0.22.0-py2.py3-none-any.whl
Collecting cffi>=1.7 (from cryptography>=1.9->pyopenssl->-r requirements.txt (line 11))
  Using cached cffi-1.10.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting azure-mgmt-nspkg (from azure-mgmt-cdn==0.30.0rc5->azure-mgmt==0.30.0rc5->azure==2.0.0rc5->-r requirements.txt (line 7))
  Using cached azure_mgmt_nspkg-2.0.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.7->cryptography>=1.9->pyopenssl->-r requirements.txt (line 11))
Building wheels for collected packages: ansible
  Running setup.py bdist_wheel for ansible ... done
  Stored in directory: /home/kevingrij/.cache/pip/wheels/16/54/d0/7f2f8b5c8c92fc46ffb20cf827299922081c1c4d121fff1806
Successfully built ansible
Installing collected packages: ipaddress, six, idna, asn1crypto, enum34, pycparser, cffi, cryptography, secretstorage, keyring, chardet, certifi, urllib3, requests, oauthlib, requests-oauthlib, isodate, msrest, python-dateutil, PyJWT, adal, msrestazure, pynacl, pyasn1, bcrypt, paramiko, MarkupSafe, jinja2, PyYAML, pycrypto, ansible, dopy, boto, futures, docutils, jmespath, botocore, s3transfer, boto3, azure-nspkg, azure-common, azure-batch, azure-servicemanagement-legacy, azure-graphrbac, azure-storage, azure-mgmt-nspkg, azure-mgmt-cdn, azure-mgmt-powerbiembedded, azure-mgmt-notificationhubs, azure-mgmt-authorization, azure-mgmt-batch, azure-mgmt-storage, azure-mgmt-resource, azure-mgmt-web, azure-mgmt-network, azure-mgmt-logic, azure-mgmt-keyvault, azure-mgmt-scheduler, azure-mgmt-compute, azure-mgmt-cognitiveservices, azure-mgmt-redis, azure-mgmt-commerce, azure-mgmt, azure-servicebus, azure, apache-libcloud, pyopenssl
Exception:
Traceback (most recent call last):
  File "/home/kevingrij/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/kevingrij/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/kevingrij/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/kevingrij/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/kevingrij/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/kevingrij/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/kevingrij/.local/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/ipaddress.py'

### Summary of the problem
Getting the following error on configuration:
ERROR! no action detected in task

The error appears to have been in '/home/algo/roles/cloud-digitalocean/tasks/main.yml': line 72, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Tag the droplet
  ^ here

### Steps to reproduce the behavior
pip install -r requirements.txt was giving me an error

### The way of deployment (cloud or local)
cloud

### Full log

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 2

Enter your aws_access_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
Note: Make sure to use an IAM user with an acceptable policy attached (see https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md).
[pasted values will not be displayed]
[AKIA...]:

Enter your aws_secret_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
[pasted values will not be displayed]
[ABCD...]:

Name the vpn server:
[algo]: Lola

  What region should the server be located in?
    1.   us-east-1           US East (N. Virginia)
    2.   us-east-2           US East (Ohio)
    3.   us-west-1           US West (N. California)
    4.   us-west-2           US West (Oregon)
    5.   ap-south-1          Asia Pacific (Mumbai)
    6.   ap-northeast-2      Asia Pacific (Seoul)
    7.   ap-southeast-1      Asia Pacific (Singapore)
    8.   ap-southeast-2      Asia Pacific (Sydney)
    9.   ap-northeast-1      Asia Pacific (Tokyo)
    10.  eu-central-1        EU (Frankfurt)
    11.  eu-west-1           EU (Ireland)
    12.  eu-west-2           EU (London)
    13.  ca-central-1        Canada (Central)
    14.  sa-east-1           São Paulo
Enter the number of your desired region:
[1]: 1

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: y

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: y

List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
: Thyve

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: y

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: y

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: y

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: y
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/kevingrij/algo/roles/cloud-digitalocean/tasks/main.yml': line 72, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: Tag the droplet
      ^ here

The error appears to have been in '/home/kevingrij/algo/roles/cloud-digitalocean/tasks/main.yml': line 72, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: Tag the droplet
      ^ here

**Comment by kevingrijalva** [comment]
might be related to this https://github.com/trailofbits/algo/issues/607

**Comment by kevingrijalva** [comment]
I just reinstalled everything and it did the trick. Please close this :)
