### ISSUE TITLE
Installation failed due to failure in installing some dependencies required

### ISSUE THREAD

**Issue by brijq** [trailofbits/algo#737]
### OS / Environment

Google Cloud 

### Ansible version

Fail to install

### Version of components from `requirements.txt`

Failed to install

### Summary of the problem
Failed to install some dependencies

### Steps to reproduce the behavior
./algo

### The way of deployment (cloud or local)
Local installation into Cloud

### Expected behavior
Just expecting installation success

### Actual behavior
./algo: line 73: ansible-playbook: command not found

### Full log

shorten logs as I filter out the issues:

 configure: error: in `/private/var/folders/64/h98pzhnd31d0p5q4_3f_sxwr0000gp/T/pip-build-ME9jFL/pycrypto':
  configure: error: C compiler cannot create executables
  See `config.log' for more details
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/64/h98pzhnd31d0p5q4_3f_sxwr0000gp/T/pip-build-ME9jFL/pycrypto/setup.py", line 456, in <module>
      core.setup(**kw)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/brian.oh/Desktop/algo-master/env/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/64/h98pzhnd31d0p5q4_3f_sxwr0000gp/T/pip-build-ME9jFL/pycrypto/setup.py", line 251, in run
      self.run_command(cmd_name)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/64/h98pzhnd31d0p5q4_3f_sxwr0000gp/T/pip-build-ME9jFL/pycrypto/setup.py", line 278, in run
      raise RuntimeError("autoconf error")
  RuntimeError: autoconf error
  
  ----------------------------------------
  Failed building wheel for pycrypto
  Running setup.py clean for pycrypto

 configure: error: in `/private/var/folders/64/h98pzhnd31d0p5q4_3f_sxwr0000gp/T/pip-build-ME9jFL/pycrypto':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/64/h98pzhnd31d0p5q4_3f_sxwr0000gp/T/pip-build-ME9jFL/pycrypto/setup.py", line 456, in <module>
        core.setup(**kw)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/brian.oh/Desktop/algo-master/env/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/64/h98pzhnd31d0p5q4_3f_sxwr0000gp/T/pip-build-ME9jFL/pycrypto/setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/64/h98pzhnd31d0p5q4_3f_sxwr0000gp/T/pip-build-ME9jFL/pycrypto/setup.py", line 278, in run
        raise RuntimeError("autoconf error")
    RuntimeError: autoconf error
    
    ----------------------------------------
Command "/Users/brian.oh/Desktop/algo-master/env/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/64/h98pzhnd31d0p5q4_3f_sxwr0000gp/T/pip-build-ME9jFL/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/64/h98pzhnd31d0p5q4_3f_sxwr0000gp/T/pip-LQ7gny-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/brian.oh/Desktop/algo-master/env/include/site/python2.7/pycrypto" failed with error code 1 in /private/var/folders/64/h98pzhnd31d0p5q4_3f_sxwr0000gp/T/pip-build-ME9jFL/pycrypto/

**Comment by JuntaoZhong** [comment]
I have trouble installing dependencies as well, what could be the problem? I am using AWS Ubuntu.
![capture](https://user-images.githubusercontent.com/41411482/52979643-6f29ec80-338b-11e9-9893-ce1eb0fe0e57.PNG)

**Comment by davidemyers** [comment]
@JuntaoZhong Make sure you are running that set of commands from the Algo source directory.

**Comment by JuntaoZhong** [comment]
> @JuntaoZhong Make sure you are running that set of commands from the Algo source directory.

By source directory, do you mean a "cd algo-master" into the algo folder?
What's the command to enter source directory?
Thanks

![image](https://user-images.githubusercontent.com/41411482/52980652-009b5d80-3390-11e9-8352-522ad413281f.png)

**Comment by davidemyers** [comment]
In the first screenshot you're running as `root`, but in the second you're running as `ubuntu`.  I'm guessing your `algo-master` directory is owned by `root` and therefore unwritable by `ubuntu`?

**Comment by JuntaoZhong** [comment]
Thank you! I think that was the problem
