### ISSUE TITLE
Is Ubuntu 14.04 supported? Virtualenv pip failing to install final dependencies

### ISSUE THREAD

**Issue by priestsRcool** [trailofbits/algo#801]
### OS / Environment

Ubuntu 14.04.5 LTS

### Ansible version

ansible 2.2.0.0

### Summary of the problem
virtualenv pip can't install final dependencies

### Steps to reproduce the behavior
# install python dependencies successfully (step 3 - https://github.com/trailofbits/algo/blob/master/README.md)

$ cd algo-master
$ python -m virtualenv env && source env/bin/activate && python -m pip install -U pip
New python executable in env/bin/python
Installing setuptools, pip...done.
/home/fionn/scratch/algo-master/env/bin/python: cannot import name HeaderParsingError; 'pip' is a package and cannot be directly executed
$ pip --version
Traceback (most recent call last):
  File "/home/fionn/scratch/algo-master/env/bin/pip", line 7, in <module>
    from pip import main
  File "/home/fionn/scratch/algo-master/env/local/lib/python2.7/site-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/fionn/scratch/algo-master/env/local/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/fionn/scratch/algo-master/env/local/lib/python2.7/site-packages/pip/download.py", line 22, in <module>
    from pip._vendor import requests, six
  File "/home/fionn/scratch/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/fionn/scratch/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/fionn/scratch/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/fionn/scratch/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/fionn/scratch/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
  File "/home/fionn/scratch/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 33, in <module>
    from .connection import (
  File "/home/fionn/scratch/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 41, in <module>
    from .util import (
  File "/home/fionn/scratch/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/__init__.py", line 5, in <module>
    from .response import is_fp_closed
  File "/home/fionn/scratch/algo-master/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/response.py", line 4, in <module>
    from ..exceptions import HeaderParsingError
ImportError: cannot import name HeaderParsingError

### The way of deployment (cloud or local)
local

**Comment by dguido** [comment]
pip is not having a problem installing dependencies, Ubuntu is having trouble installing pip at all. Try installing pip another way.
